// Code generated by pg-bindings generator. DO NOT EDIT.

//go:build sql_integration

package postgres

import (
	"context"
	"testing"

	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres/pgtest"
	"github.com/stackrox/rox/pkg/sac"
	"github.com/stackrox/rox/pkg/testutils"
	"github.com/stretchr/testify/suite"
)

type ClusterRegistryMirrorSetsStoreSuite struct {
	suite.Suite
	store  Store
	testDB *pgtest.TestPostgres
}

func TestClusterRegistryMirrorSetsStore(t *testing.T) {
	suite.Run(t, new(ClusterRegistryMirrorSetsStoreSuite))
}

func (s *ClusterRegistryMirrorSetsStoreSuite) SetupSuite() {

	s.testDB = pgtest.ForT(s.T())
	s.store = New(s.testDB.DB)
}

func (s *ClusterRegistryMirrorSetsStoreSuite) SetupTest() {
	ctx := sac.WithAllAccess(context.Background())
	tag, err := s.testDB.Exec(ctx, "TRUNCATE cluster_registry_mirror_sets CASCADE")
	s.T().Log("cluster_registry_mirror_sets", tag)
	s.NoError(err)
}

func (s *ClusterRegistryMirrorSetsStoreSuite) TearDownSuite() {
	s.testDB.Teardown(s.T())
}

func (s *ClusterRegistryMirrorSetsStoreSuite) TestStore() {
	ctx := sac.WithAllAccess(context.Background())

	store := s.store

	clusterRegistryMirrorSet := &storage.ClusterRegistryMirrorSet{}
	s.NoError(testutils.FullInit(clusterRegistryMirrorSet, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))

	foundClusterRegistryMirrorSet, exists, err := store.Get(ctx, clusterRegistryMirrorSet.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundClusterRegistryMirrorSet)

}
